version: "2.1"

services:
  reviews:
    build: .
    command: yarn test --exit
    ports:
      - 3001:3000
    depends_on:
      reviewsDb:
        condition: service_healthy

  reviewsDb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - reviewsDb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  reviewsDb:
