version: "3.1"

services:
  review:
    build: .
    restart: always
    ports:
      - 3001:3000
    networks:
      - djarn

  reviewsDb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - djarn

networks:
  djarn:
    external: true
